CREATE TABLE `customer_files` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileNumber` varchar(20) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`consultationDate` varchar(100),
	`assignee` varchar(255),
	`companion` varchar(255),
	`source` varchar(255),
	`contractDeposit` varchar(255) DEFAULT '',
	`commission` varchar(255) DEFAULT '',
	`consent` varchar(255) DEFAULT '',
	`realEstateFile` varchar(255) DEFAULT '',
	`businessCardCollection` varchar(255) DEFAULT '',
	`nameplate` varchar(255) DEFAULT '',
	`rentalManagement` varchar(255) DEFAULT '',
	`propertyAddress` text,
	`propertyPrice` varchar(100),
	`miscCosts` varchar(100),
	`totalFinancing` varchar(100),
	`buildingArea` varchar(100),
	`landArea` varchar(100),
	`buildYear` varchar(100),
	`structure` varchar(100),
	`layout` varchar(100),
	`phase` enum('consultation','pre_review','review','contract','final_settlement','completed','cancelled') NOT NULL DEFAULT 'consultation',
	`financialInstitution` varchar(255),
	`broker` varchar(255),
	`notes` text,
	`slackMessageTs` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customer_files_id` PRIMARY KEY(`id`)
);
